name: "Azure Blob Storage Check Blob Exists"
author: "Loïs Postula <lois@postu.la>"
description: "Check if a blob exists in Azure Blob Storagee"
branding:
  icon: "box"
  color: "green"
inputs:
  repository:
    description: "Name of the repository"
    required: true
  username:
    description: "The shared access signature token for the storage account. Either connection_string or sas_token must be supplied"
    required: true
  password:
    description: "The name of the storage account. Required if sas_token is used"
    required: true
  image_name:
    description: "The name of the image to check"
    required: true
  version:
    description: "The version of the image to check"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'

outputs:
  exists:
    description: "True if the docker image exists"
